"use client";

import { Calendar, Search, ChevronRight, UserCircle2, Loader2, IndianRupee } from "lucide-react";
import { useState, useEffect, useMemo } from "react";
import { useRouter } from "next/navigation";

export default function BookingPage() {
  const [bookings, setBookings] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const router = useRouter();

  useEffect(() => {
    fetchBookings();
  }, []);

  const fetchBookings = async () => {
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || "/api/proxy";
      const res = await fetch(`${apiUrl}/api/bookings`);
      if (res.ok) {
        const data = await res.json();
        setBookings(data);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const filteredBookings = useMemo(() => {
    if (!searchQuery.trim()) return bookings;
    const lowerQ = searchQuery.toLowerCase();
    return bookings.filter((b) => {
      const name = `${b.customer?.firstName || ""} ${
        b.customer?.lastName || ""
      }`.toLowerCase();
      const bookingNo = (b.bookingNumber || "").toLowerCase();
      const unitNo = (b.unit?.unitNumber || "").toLowerCase();
      const handledBy = `${b.salesExec?.firstName || ""} ${
        b.salesExec?.lastName || ""
      }`.toLowerCase();
      return (
        name.includes(lowerQ) ||
        bookingNo.includes(lowerQ) ||
        unitNo.includes(lowerQ) ||
        handledBy.includes(lowerQ)
      );
    });
  }, [bookings, searchQuery]);

  return (
    <div className="p-4 md:p-8 max-w-[1600px] mx-auto space-y-6 animate-enter">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-extrabold text-[var(--text-primary)] tracking-tight flex items-center gap-2.5 m-0">
            <div className="w-8 h-8 rounded-xl bg-purple-50 flex items-center justify-center text-[var(--brand-700)]">
              <Calendar size={18} />
            </div>
            <span>Team Bookings & Finalized Deals</span>
          </h1>
          <p className="text-xs text-[var(--text-muted)] font-medium mt-0.5 m-0">
            Review finalized unit bookings generated by your sales executives
          </p>
        </div>
        <div className="relative w-full md:w-80">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            placeholder="Search customer, booking #, unit, exec…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full h-9 pl-9 pr-3 bg-white border border-slate-200 rounded-xl text-base sm:text-xs font-semibold text-[var(--text-primary)] outline-none focus:border-[var(--brand-600)] focus:ring-2 focus:ring-purple-500/15 transition-all shadow-2xs placeholder:text-slate-400"
          />
        </div>
      </div>

      {loading ? (
        <div className="min-h-[40vh] flex flex-col items-center justify-center gap-3">
          <Loader2 className="w-8 h-8 text-[var(--brand-600)] animate-spin" />
          <p className="text-xs font-semibold text-[var(--text-muted)]">
            Loading team bookings…
          </p>
        </div>
      ) : filteredBookings.length === 0 ? (
        <div className="py-16 flex flex-col items-center justify-center bg-slate-50/60 rounded-3xl border border-slate-200 border-dashed space-y-2">
          <div className="w-10 h-10 rounded-2xl bg-white flex items-center justify-center text-slate-400 border border-slate-200 shadow-2xs">
            <Calendar size={18} />
          </div>
          <h3 className="text-xs font-bold text-slate-700 m-0">
            {searchQuery ? "No matching bookings found" : "No Bookings Recorded Yet"}
          </h3>
          <p className="text-[11px] text-[var(--text-muted)] font-medium m-0">
            {searchQuery
              ? "Try adjusting your search criteria."
              : "Finalized bookings from your sales executives will appear here."}
          </p>
        </div>
      ) : (
        <div className="bg-white rounded-3xl border border-slate-200/80 shadow-2xs overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs whitespace-nowrap">
              <thead className="bg-slate-50/80 border-b border-slate-100">
                <tr>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider w-12">
                    #
                  </th>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider">
                    Customer Name
                  </th>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider">
                    Phone
                  </th>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider">
                    Booking No.
                  </th>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider">
                    Unit
                  </th>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider">
                    Handled By
                  </th>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider text-right">
                    Agreed Price
                  </th>
                  <th className="px-5 py-3 text-[10px] font-extrabold text-[var(--text-muted)] uppercase tracking-wider w-10"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredBookings.map((booking, index) => {
                  const phone =
                    booking.customer?.lead?.phone ||
                    booking.customer?.phone ||
                    "N/A";
                  return (
                    <tr
                      key={booking.id}
                      onClick={() =>
                        router.push(
                          `/dashboard/sales-manager/lead-management/${booking.customer?.lead?.id}`
                        )
                      }
                      className="hover:bg-slate-50/80 cursor-pointer transition-colors group"
                    >
                      <td className="px-5 py-3.5 text-slate-400 font-bold tabular-nums">
                        {index + 1}
                      </td>
                      <td className="px-5 py-3.5 font-bold text-[var(--text-primary)] group-hover:text-[var(--brand-700)] transition-colors">
                        {booking.customer?.firstName} {booking.customer?.lastName}
                      </td>
                      <td className="px-5 py-3.5 text-slate-600 font-semibold tabular-nums">
                        {phone}
                      </td>
                      <td className="px-5 py-3.5">
                        <span className="bg-purple-50 text-[var(--brand-700)] px-2 py-0.5 rounded-md text-[10px] font-extrabold tracking-wider uppercase border border-purple-200/60 tabular-nums">
                          {booking.bookingNumber}
                        </span>
                      </td>
                      <td className="px-5 py-3.5 text-slate-900 font-extrabold tabular-nums">
                        {booking.unit?.unitNumber || "N/A"}
                      </td>
                      <td className="px-5 py-3.5 text-slate-600 font-semibold">
                        <div className="flex items-center gap-1.5">
                          <UserCircle2 size={14} className="text-slate-400" />
                          <span>
                            {booking.salesExec?.firstName || "Executive"}{" "}
                            {booking.salesExec?.lastName || ""}
                          </span>
                        </div>
                      </td>
                      <td className="px-5 py-3.5 text-emerald-700 font-extrabold text-right tabular-nums">
                        ₹{Number(booking.agreedPrice).toLocaleString("en-IN")}
                      </td>
                      <td className="px-5 py-3.5 text-right">
                        <div className="w-6 h-6 rounded-lg bg-slate-100 group-hover:bg-purple-100 flex items-center justify-center transition-colors">
                          <ChevronRight
                            size={14}
                            className="text-slate-400 group-hover:text-[var(--brand-700)]"
                          />
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
