// ============================================================================
// Resyl — Voice TTS Providers Constants & Voice Mappings
// ============================================================================

export const ELEVEN_VOICE_MAP: Record<string, string> = {
  rachel: '21m00Tcm4TlvDq8ikWAM',
  adam: 'pNInz6obpgDQGcFmaJgB',
  antoni: 'ErXwobaYiN019PkySvjV',
  josh: 'TxGEqnHWrfWFTfGW9XjX',
  sarah: 'EXAVITQu4vr4xnSDxMaL',
  domi: 'AZnzlk1XvdvUeBnXmlld',
  michael: 'flq6f7yk4E4fJM5XTYuZ',
  bella: 'EXAVITQu4vr4xnSDxMaL',
  adrian: 'pNInz6obpgDQGcFmaJgB',
  jenny: '21m00Tcm4TlvDq8ikWAM',
  charlie: 'IKne3meq5aSn9XLyUdCD',
  george: 'JBFqnCBsd6RMkjVDRZzb',
  emily: 'LcfcDJNigL5wcJA5FgSe',
  nicole: 'piTKgcLEGmPE4e6mEKli',
  callum: 'N2lVS1w4EtoT3dr4eOWO',
  liam: 'TX3LPaxmHKxFdv7VOQHJ',
  will: 'bIHbv24MWmeRgasZH58o',
  brian: 'nPczCjzI2devNBz1zQrb',
  viraj: 'iWNf11sz1GrUE4ppxTOL',
};

export const DEEPGRAM_MAP: Record<string, string> = {
  asteria: 'aura-asteria-en',
  angie: 'aura-asteria-en',
  luna: 'aura-luna-en',
  stella: 'aura-stella-en',
  athena: 'aura-asteria-en',
  hera: 'aura-luna-en',
  orion: 'aura-orion-en',
  zeus: 'aura-zeus-en',
  helios: 'aura-helios-en',
  orpheus: 'aura-orion-en',
  arcas: 'aura-zeus-en',
  perseus: 'aura-helios-en',
};

export const CARTESIA_VOICE_MAP: Record<string, string> = {
  sarah: 'a0e99841-438c-4a64-b679-ae501e7d6091',
  james: '694f9389-aac1-45b6-b726-9d9369183238',
  katie: 'f114a467-c40a-4db8-964d-aaba01609c68',
  brooke: 'e90c6678-f0d3-4767-970c-26b69b4c32ea',
  cali: 'a0e99841-438c-4a64-b679-ae501e7d6091',
};

export const SARVAM_SPEAKERS: string[] = [
  'shubh',
  'aditya',
  'ritu',
  'priya',
  'neha',
  'rahul',
  'pooja',
  'rohan',
  'simran',
  'kavya',
  'amit',
  'dev',
  'ishita',
  'shreya',
  'ratan',
  'varun',
  'manan',
  'sumit',
  'roopa',
  'kabir',
  'aayan',
  'ashutosh',
  'advait',
  'anand',
  'tanya',
  'tarun',
  'sunny',
  'mani',
  'gokul',
  'vijay',
  'shruti',
  'suhani',
  'mohit',
  'kavitha',
  'rehan',
  'soham',
  'rupali',
  'ananya',
  'arvind',
  'meera',
];
